name: Test Custom GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run custom GitHub Action
      id: get-date-time
      uses: Gayathri-Gadde/Generate-Date-and-Time@v1.4
      with:
        function-url: 'https://t-gg-fapp.azurewebsites.net/api/Returndateandtime?'

    - name: Output current date and time
      run: echo "Current Date and Time from Azure Function ${{ steps.get-date-time.outputs.currentDateTime }}"
